### ISSUE TITLE
Addon isn't working on Android.

### ISSUE THREAD

**Issue by hudokkow** [kodi-pvr/pvr.hdhomerun#1]
@zcsizmadia, one of our team members tested your addon with Android using today's Kodi master and something is wrong:

> the Addon doesn't work for Android. It keeps saying no pvr add-on enabled. I make sure it's enabled but afterwards it disabled again

**Comment by zcsizmadia** [comment]
1.Could you send me the android zip package? 

2. I only have Windows environment and using VirtualBox with Ubuntu to build and test on linux. Is there any cross compile environment for android available from ubuntu or windows? If yes how does it work with the cmake?

Thanks!

**Comment by zcsizmadia** [comment]
I've just installed the arm-linux-gnueabihf and could compile the android package. I will check it tomorrow if it is working.

I'd appreciate if you could still send me your zip package.

**Comment by zcsizmadia** [comment]
It seems the problem is that the addon has to be configured, even with the default settings. After that TV  and addon can be enabled.

**Comment by MartijnKaijser** [comment]
Indeed you first have open addon settings and hit ok. Think other addons had the same and made sure the it just takes the default values. If no userdate  settings.xml take settings values. 
Not sure if we have to make sure kodi interface fixes thus "flaw". At least this works for python addons

**Comment by zcsizmadia** [comment]
I've added needs_configuration="false" to addon.xml and seems to solve the issue. My guess is that Kodi for some reason reads true for that setting if not specified and stops loading the addon (PVRClient.cpp).

**Comment by zcsizmadia** [comment]
"needs_configuration"="false" in addon.xml seems to solve the problem
