### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by nb2a** [kodi-pvr/pvr.hdhomerun#13]
Code:
18:38:45  89.346893 T:1754264480   ERROR: Unable to load /usr/lib/kodi/addons/pvr.hdhomerun/pvr.hdhomerun.so, reason: /usr/lib/kodi/addons/pvr.hdhomerun/pvr.hdhomerun.so: undefined symbol: IsRealTimeStream

This add-on doesn't support API 4.2.0. Open an issue on https://github.com/kodi-pvr/pvr.hdhomerun - if there's no sign of an update soon I'll be forced to drop it from the build (as I recently did with pvr.vuplus). No point building broken and unsupported add-ons.

**Comment by zcsizmadia** [comment]
Updated to PVR API 4.2.0

**Comment by nb2a** [comment]
Thank you be well
