### ISSUE TITLE
Make use of the official libhdhomerun library from Silicondust?

### ISSUE THREAD

**Issue by Hedda** [kodi-pvr/pvr.hdhomerun#19]
SiliconDust has now released their own official open source library called libhdhomerun with an API that implements the commands protocol need for communicating with Silicondust HDHomeRun TV tuners.

https://github.com/Silicondust/libhdhomerun

Might be a good idea to start using this library now and keep updating it so that you do not need to maintain your own command protocols libraries for HDHomeRun communications?

**Comment by zcsizmadia** [comment]
Thanks for your suggestion. Only in Windows we compile the libhdhomerun from source, other platform use it as an external depend package, installing it via apt-get or brew. SD must  release regularly into these package sources with robust versioning to be able to use it  on all platforms. Until that point we are kind of stuck with one well known version (20150826), which is available as a source code package, and a binary package for Linux and OSX.
