### ISSUE TITLE
Channel numbers

### ISSUE THREAD

**Issue by rome1983** [kodi-pvr/pvr.hdhomerun#21]
Hi, in the kodi skin my channel numbers are not used, instead kodi numbers my channels starting from one even with use channel numbers from backend checked. For example my first channel I get 1 4.1 wwl  and so on. In the new estuary skin it does that in the channels section but on the right side where shows eit data it shows the correct channel numbers. Would it be possible to fix this?  Add-on is the best for PVR in US. Thanks.

**Comment by zcsizmadia** [comment]
It sounds like a skin issue. If I understand correctly you do not want to see the logical channel number in your channels list. If that is the case, here is how to remove it by editing your skin xml files:

1. Open "Kodi installation folder\addons\skin.estuary\1080i\MyPVRChannels.xml
2. Search for $INFO[ListItem.ChannelNumberLabel]
3. You should find 2 instances, something like <label>$INFO[ListItem.ChannelNumberLabel]</label>
4. Replace them with an empty string, so you should have them as <label></label>
5. Restart Kodi

Hope this helps.

**Comment by rome1983** [comment]
Thanks for the reply. I have 33 OTA channels and I want to remove the  1 through 33 before each channel number. Instead of 1 4.1wwl it should show 4.1wwl .

**Comment by zcsizmadia** [comment]
In that case the XML modification should help you. Look around thos xml files, and you can really fine tune the skin to your liking. Let me know if you need help with the skin xml files.

**Comment by rome1983** [comment]
K, I will give it a try and report back. Thanks

**Comment by rome1983** [comment]
I think I  found what the issue is, with the add-on channel name and number is not independent. ChannelNumberLabel does not work but ChannelName does and it gives me number and name instead of just name.
