### ISSUE TITLE
channels 

### ISSUE THREAD

**Issue by rome1983** [kodi-pvr/pvr.hdhomerun#27]
Is there any way to separate channel numbers from channel names to avoid skin issues.

**Comment by zcsizmadia** [comment]
By seperation you mean not having the channel numbers in the name? Could you send me a screenshot of your skin, with the output you would prefer?

**Comment by rome1983** [comment]
Thanks, never mind I just edited the skin files. I do have another question, is signal to noise and signal quality supported?
