### ISSUE TITLE
does not compile on android

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.hdhomerun#28]
master does not compile on android, several source files fail to compile due to

<pre>
/hdhomerun_os_posix.h:33:23: fatal error: sys/timeb.h: No such file or directory
 #include &ltsys/timeb.h>
</pre>

@koying due you have an idea for a fix?

**Comment by koying** [comment]
There is no timeb.h on latest Android toolchain.

FWIW, ftime(timeb) is considered obsolete: http://man7.org/linux/man-pages/man3/ftime.3.html#CONFORMING_TO

**Comment by zcsizmadia** [comment]
Updated libhdhomerun dependency by using https://github.com/Silicondust/libhdhomerun instead if the tgz source package from the silicondust website. It seems the latest version got rid of timeb.h include. Please let me know if it solves the Android build. Thanks!

**Comment by ksooo** [comment]
just checked. builds now. thanks.
