### ISSUE TITLE
Support for Multiple HDR Boxes

### ISSUE THREAD

**Issue by MatthewLundberg** [kodi-pvr/pvr.hdhomerun#42]
The reason that each channel shows up for each tuner box, is because the std::set guideNumberSet is in the scope for each tuner.

Moving the declaration to outside the loop, at the top of the function HDHomeRunTuners::Update(int nMode) does cause each channel to show up exactly once.  However this is not a complete fix, as then you can only tune channels from the first tuner box found.  If all tuners in the box are in use, the attempt to tune the channel fails.

The real fix would seem to be keeping a list of tuners which support each channel found, and then iterating through this list when an attempt is made to tune the channel.  These should also be separated based on the channelmap in use for that tuner, to handle the case where a user has both OTA and cable service -- I personally know someone doing this, but I don't think he's using Kodi (yet).

Are you actively working on this problem?  I ask because I have forked your code and can fix it, but don't really need to be duplicating efforts.

**Comment by zcsizmadia** [comment]
Go ahead with the PR, I am not working on it. Thanks for your help!

**Comment by MatthewLundberg** [comment]
It's likely to be a few weeks before I get something workable.  But when I do, I don't have the facilities to test on all OS's.  I can get Kodi and the PVR to build and run on Linux, but Windows is kicking my behind (and I have a lot of Windows experience!).  Think you can help test it once I get something done, before I make a pull request?
