### ISSUE TITLE
Bug in class HDHomeRunTuners::AutoLock(HDHomeRunTuners&)

### ISSUE THREAD

**Issue by MatthewLundberg** [kodi-pvr/pvr.hdhomerun#43]
HDHomeRunTuners.h:61 AutoLock(HDHomeRunTuners& p) : m_p(&p) { m_p->Unlock(); }

This constructor should call m_p->Lock().

However, I'm not sure that this constructor is actually called.

**Comment by zcsizmadia** [comment]
Good catch! Feel free to create a PR to fix it.

**Comment by MatthewLundberg** [comment]
I will need additional locked objects with the multi-tuner work, so I will put the fix in there.  As this doesn't appear to be actually called, the fix can wait.
