### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by EdTheC** [kodi-pvr/pvr.hdhomerun#6]
I don't see a zip file, and nothing like this in Kodi addons. Please list the steps to get it installed for us newbies. Thanks!

**Comment by zcsizmadia** [comment]
1. For non-linux (e.g win32, Android, ...) use the latest nightly builds for 16.0 or higher.

2. For linux, check the instructions how to install the nightly builds:
http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

You should do something like this:
sudo add-apt-repository ppa:team-xbmc/xbmc-nightly
sudo apt-get update
sudo apt-get install kodi
sudo apt-get install kodi-pvr-hdhomerun
