### ISSUE TITLE
[Feature Request] Record TV (DVR feature) save video stream to local disk

### ISSUE THREAD

**Issue by Hedda** [kodi-pvr/pvr.hdhomerun#7]
I like to make a feature suggestion, that is to add recording functionality into this PVR client addon.

From a user-experince point of view have the ability to "record to disk" inside this native HDHomeRun PVR client addon. In function for this PVR client addon to be able act a DVR (Digital Video Recorder) on its own when used in Kodi. That is, for the PVR client addon itself to save individual video streams to local disk directory/folder. Preferably for the PVR client addon to even save as video files in MPEG-TS (.TS) format just like real DVRs.

This ability to record can also add more features which have dependency on recording, like the ability to "Pause" and "Rewind" Live TV if could add the possibility to continuously record a video streaming from a networked-attatched HDHomeRun tuner to a series of temporary files in a look, again acting just like a read stand-alone DVR box.

Compating to other PVR client addons for Kodi, all such a function is normally located and dependent in an external PVR backend instead of the PVR client addon itself, but this addon is kind-of special and somewhat unique in that it connects to the (network-attached) TV-tuner directly, streaming directly from, so it does not go through a third-party PVR backend at all which can bring such recording functionality. And in addition it would be very nice to have the ability for the video files to be saved locally directlly on an Android device instead of on the PVR backend.

**Comment by Hedda** [comment]
Here is a fork of the Simple IPTV PVR client with code which features a simple recording feature which adds timeshifting functionality:

https://github.com/simphax/pvr.iptvsimple

@zcsizmadia   would you reject a pull request for such features to the Stalker (or native HDHomeRun) PVR client addons? Please note that Nate from team Kodi posted in native HDHomeRun PVR client addon forum thread not long ago and requested this feature himself.

Point is for this addons to have this capability nativly is just these few unique stand-alone client addons without the need to use a backend.

**Comment by Hedda** [comment]
@zcsizmadia What is your opionion on this? Would it be interested in copying and implementing rkubera's native code for recording into your stand-alone HDHomeRun PVR client addon?

https://github.com/rkubera/pvr.iptvsimple/

**Comment by Hedda** [comment]
@zcsizmadia What is your opionion on this? Do you think that Team-Kodi developers would reject a pull request for such local record features added to this native HDHomeRun PVR client addon? If so, why?

**Comment by zcsizmadia** [comment]
It is definitely a plan to add this feature. Unfortunately in short term I do not think I can find the time. I am really open for pull requests if someone takes the initiative to modify the addon.

**Comment by Hedda** [comment]
@zcsizmadia That is cool. Have you looked at code by rkubera for recording to a PVR client addon?

https://github.com/simphax/pvr.iptvsimple/tree/master/src

Other than adding libexecstream the recording functionality looks to be pretty well contained in code.

**Comment by Hedda** [comment]
FYI; might be a little off-topic but some competition could maybe give a little insentive to add a record feature to the HDHomeRun PVR native addon for Kodi;

Plex have in partnership with SiliconDust now added native DVR recording support in to Plex Media Server from HDHomeRun network tuners. For more info read:

https://www.plex.tv/blog/air-human-plex-dvr-divine/
https://www.plex.tv/features/dvr/
https://support.plex.tv/hc/en-us/articles/226074728-Setting-Up-Recordings
https://support.plex.tv/hc/en-us/articles/225976308-Manage-Your-Recordings
https://support.plex.tv/hc/en-us/sections/205778607-DVR

**Comment by Hedda** [comment]
Was this closed because it is a bad idea or just because no one wants it?

**Comment by Hedda** [comment]
@zcsizmadia any comments on this?

**Comment by zcsizmadia** [comment]
I am not planning to add this feature to the addon as of now. I think this should be implemented as part of the PVR engine in Kodi, instead of on the individual add-on level. I suggest to make your request with the Kodi development team.

**Comment by Hedda** [comment]
@zcsizmadia FYI; I took this to Team Kodi and the feedback I got from the members that replied was that "PVR recoding will never be implemented in Kodi's core" and the reasoning for this is that recording could be abused by IPTV addons to illegally record online streams. 

So if this is the opionion of all Kodi team members then I see no other solution than to implement recording in the individual HDHomeRun PVR addon, as it will "never" be implemented into Kodi's core.

**Comment by fuzzard** [comment]
Theres a PR that implements this in a rough fashion that i made a couple months back. https://github.com/kodi-pvr/pvr.hdhomerun/pull/67
I havent bothered to keep working on it, but it works with my limited testing and builds against current kodi master

**Comment by MatthewLundberg** [comment]
As I've said before, the recording should be done by a service on Windows or daemon on Linux, and be instructed by Kodi.  This increases the complexity, as two cooperating programs are required.  And of course, there's another PVR that does exactly this, but unfortunately the DVR portion is not free.
