### ISSUE TITLE
signal strength and signal to noise quality  

### ISSUE THREAD

**Issue by rome1983** [kodi-pvr/pvr.hdhomerun#84]
hdhomerun_config FFFFFFFF get /tuner0/status returns the info needed 
ch=8vsb:647000000 lock=8vsb ss=100 snq=98 seq=100 bps=14647456 pps=1391

Anyway to get ss and snq into the gui?

**Comment by fuzzard** [comment]
https://forum.kodi.tv/showthread.php?tid=343729

I elaborated a little more in that thread about signal
